### ISSUE TITLE
extension headers name

### ISSUE THREAD

**Issue by nmav** [thomas-fossati/draft-tls-ext-header#3]
While writing the text for the negotiation, I realized that the name "extension headers" is confusing when described in a section about TLS (handshake) extensions. We may need a more distinctive name.

Possible options:
 * record headers
 * record header extensions
 * ???

**Comment by thomas-fossati** [comment]
You are right.  I'd go with the second (record header extensions).

**Comment by thomas-fossati** [comment]
Closing (for now).  If we want to change in the future, just change the "foo" macro value.
